// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3RxW5ANVmX0acu3cd56Tx0uMbf3T4csU',
    appId: '1:1008506028199:web:856439050794f50b349b82',
    messagingSenderId: '1008506028199',
    projectId: 'invest-mkononi',
    authDomain: 'invest-mkononi.firebaseapp.com',
    storageBucket: 'invest-mkononi.firebasestorage.app',
    measurementId: 'G-MHB34S0GB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARbDGuQs6Bw8qyQBNt1i6zsNQQQfOpfV4',
    appId: '1:1008506028199:android:58ffd8479c8e1d37349b82',
    messagingSenderId: '1008506028199',
    projectId: 'invest-mkononi',
    storageBucket: 'invest-mkononi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHJnrUIn_oxCqA_HYYsbvPYHe6UR3tr2E',
    appId: '1:1008506028199:ios:20824c520d67ae1b349b82',
    messagingSenderId: '1008506028199',
    projectId: 'invest-mkononi',
    storageBucket: 'invest-mkononi.firebasestorage.app',
    iosBundleId: 'com.tsl.investmkononi.apps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHJnrUIn_oxCqA_HYYsbvPYHe6UR3tr2E',
    appId: '1:1008506028199:ios:95cca54fdebbb160349b82',
    messagingSenderId: '1008506028199',
    projectId: 'invest-mkononi',
    storageBucket: 'invest-mkononi.firebasestorage.app',
    iosBundleId: 'com.investmukononi.tsl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3RxW5ANVmX0acu3cd56Tx0uMbf3T4csU',
    appId: '1:1008506028199:web:a17e6a05055cb56a349b82',
    messagingSenderId: '1008506028199',
    projectId: 'invest-mkononi',
    authDomain: 'invest-mkononi.firebaseapp.com',
    storageBucket: 'invest-mkononi.firebasestorage.app',
    measurementId: 'G-0HF0DRGGTK',
  );
}
